// ✅ projectsData.js
import p1 from "../assets/p1.svg";
import p2 from "../assets/p2.svg";
import p3 from "../assets/p3.svg";
import p4 from "../assets/p4.svg";

export const allProjects = [
  {
    id: 1,
    img: p1,
    type: "iOS App",
    title: "Bonaire – SwiftUI-Based iOS App",
    description: "A modern brand identity with 30% increased recognition.",
    isAppStore: true,
    isPlayStore: false,
  },
  {
    id: 2,
    img: p2,
    type: "iOS App",
    title: "Advanced Pattern-Building App",
    description: "Integrates ChatGPT for intelligent guidance.",
    isAppStore: true,
    isPlayStore: false,
  },
  {
    id: 3,
    img: p3,
    type: "iOS/Android App",
    title: "Taxi Hits",
    description: "Cutting-edge mapping & secure payments.",
    isAppStore: true,
    isPlayStore: true,
  },
  {
    id: 4,
    img: p4,
    type: "Android App",
    title: "Volume Booster",
    description: "Feature-rich music player built with MVVM.",
    isAppStore: true,
    isPlayStore: false,
  },
  {
    id: 5,
    img: p1,
    type: "Web App",
    title: "Portfolio Site",
    description: "Built with React, Tailwind, and animations.",
    isAppStore: false,
    isPlayStore: false,
  },
  {
    id: 6,
    img: p2,
    type: "iOS App",
    title: "Health Tracker",
    description: "Tracks workouts & diet seamlessly.",
    isAppStore: true,
    isPlayStore: false,
  },
  {
    id: 7,
    img: p3,
    type: "Web App",
    title: "Task Manager",
    description: "Organize tasks with ease.",
    isAppStore: false,
    isPlayStore: false,
  },
  {
    id: 8,
    img: p4,
    type: "Android App",
    title: "Recipe Finder",
    description: "Find & save favorite recipes.",
    isAppStore: false,
    isPlayStore: true,
  },
  {
    id: 9,
    img: p1,
    type: "iOS App",
    title: "Fitness Buddy",
    description: "AI-based workout planner.",
    isAppStore: true,
    isPlayStore: false,
  },
  {
    id: 10,
    img: p2,
    type: "Web App",
    title: "CRM Dashboard",
    description: "Manage clients & sales pipeline.",
    isAppStore: false,
    isPlayStore: false,
  },
  {
    id: 11,
    img: p3,
    type: "Mobile App",
    title: "E-learning Platform",
    description: "Interactive courses & quizzes.",
    isAppStore: true,
    isPlayStore: true,
  },
  {
    id: 12,
    img: p4,
    type: "Web App",
    title: "Music Streaming",
    description: "Stream & discover music easily.",
    isAppStore: false,
    isPlayStore: true,
  },
];
